# API-Time-wise
@baseURL=http://localhost:8000/api/v1/tasks

### GET the task list
GET {{baseURL}}


### POST the task list
POST {{baseURL}}
Content-Type: application/json

{
    "task": "Coding",
    "hr":70,
     "abcdTest":"asfdf"
}


### PATCH the tasl list
PATCH   {{baseURL}}
Content-Type: application/json

{
   "_id": "67a7e4ecf63be0ae6e6e0207",
  "type":"bad",
 }




### Delete the task list

DELETE {{baseURL}}/67a30d66c575fcc8652c7c0c