# API-Time-wise
@baseURL=http://localhost:8000/api/v1/tasks

### GET the task list
GET {{baseURL}}


### POST the task list
POST {{baseURL}}
Content-Type: application/json

{
    "task": "Coding",
    "hr": "entry",
    "type":123
}


### PATCH the tasl list
PATCH   {{baseURL}}
Content-Type: application/json

{
    "id":2,
    "type":"bad"
}




### Delete the task list

DELETE {{baseURL}}/2